# Generated by Django 3.2.9 on 2021-11-27 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Категория')),
                ('slug', models.SlugField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория портфолио',
                'verbose_name_plural': 'Категории портфолио',
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('small_image', models.ImageField(upload_to='static/image', verbose_name='Маленькая картинка')),
                ('large_image', models.ImageField(upload_to='static/image', verbose_name='Большая картинка')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.categoryportfolio', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
    ]
